### PR TITLE
Renamed Persona to Audience

### PR DESCRIPTION
**Pull request by cesine**
## Renamed persona to audience
Audience means
"the readership of a publication"

Persona means
"the aspect of someone's character that is presented to or perceived by others.

Seems rather fishy for something that we want to be simple and easy to
find, like who would be interested in the project.

Persona is also the name of an authentication system by Mozilla
https://www.mozilla.org/en-US/persona/

When I saw the Personas.md file I thought it was something related to
Mozilla persona. We don't need devs getting confused and thinking
that doc is a persona config  or something.

What you are calling persona we do refer to as "hats" like somedays i put on my developer hat, and other days i have on my fieldlinguist hat. I am both, but not usually at the same time. The same goes for our target audience who are probably to some degree a developper or budding-developer, and to some degree, a native/heritage speaker of a low resource language, or a friend or member of a language community which we would describe as needing low-resource language techniques when it comes to making user friendly tools for them.

## Changed Linguist to RA

In my experience researching FieldDB most PIs (in theoretical linguists) delegate the task of finding tools to their students, which is why we have a plethora of PHP/MySQL student projects to build online websites for linguistics projects, because the students couldnt find "prior work" which was reusable by them within the time frame they had planned.

This means the audience isn't linguists in general. If we mark linguist here, we will receive complaints  that our page is too techy or contains projects which aren't ready to use. Rather our audience is their RAs or lab coordinators who have been tasked with the job of reading technical websites and blogs, and figuring it out. The linguists who were once RAs or who are comfortable searching for software tools, will still identify with this category and read this section.

## Terminology in general

Terminology matters, the words you choose indicates what kind of audience you are talking to. None of the words I choose for Audience, or the examples I gave, are in this document, instead it contains new words, which aren't what a developer would write. @HughP Your terminology seems fluffy to me, I'm not sure if you were making it fluffy on purpose, or if this is just how the documentation you work with sounds. The terminology is currently undermining the message: it doesn't communicate to people like me who are the target audience of the list. I don't want to erase all your work or chastise you for something you had no idea bout, and I don't really have time to do the edits, but since eddersko https://github.com/RichardLitt/endangered-languages/issues/63#issuecomment-77298348 and I https://github.com/RichardLitt/endangered-languages/issues/63#issuecomment-126507074 wrote something once about audience, maybe you could clean it up and merge it into your text?

It's hard to say which words are the problem, but maybe this one is an example:   developers dont refer to libraries or packages or codebases as "preexisting solutions" infact we call them "solutions" only to our clients and we kind of laugh at the sales guys who say they have a "solution" for us... we kind of know that there is no such thing a s a solution, and this list infact is mostly half-baked solutions which are still useful if you're desperate. lingomat https://github.com/RichardLitt/endangered-languages/issues/36#issuecomment-74362098 was asking for the list to be a list of solutions, but I think we succeeded in convincing him there are other lists for that purpose.

One quick way to see what something means is google images:
software solution are usually blue, and shinny:
https://www.google.ca/search?q=software+solutions+jokes&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMIhsTjoomNxwIVzDw-Ch0jmAUZ&biw=1920&bih=1070#tbm=isch&q=software+solutions

software libraries are usually code: 
https://www.google.ca/search?q=software+solutions+jokes&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMIhsTjoomNxwIVzDw-Ch0jmAUZ&biw=1920&bih=1070#tbm=isch&q=software+library

### CODE REVIEW

**Comment by HughP** [comment]
I gave a quick read over of you comments. Some of them make sense, especially who is actually doing the research - Some comments don't make as much sense, like the RAs doing the work. But I am not committing a lot of brain power beyond a first read today. I am coming at the personas from this persecutive:  https://en.wikipedia.org/wiki/Persona_(user_experience). The edits look good to me. I botched the merge by making a manual edit via the github interface.

**Comment by RichardLitt** [comment]
Thanks @cesine. I agree with Hugh about "personas" - this is a specific term for UX and UI designers. It is developer-centric as opposed to reader-centric, which may be the main divide between your take and Hughs. I think the issue you bring up in this PR is bigger than this PR - it should be an issue about terminology, in general. 

I disagree about switching Linguists to RAs. That is a very university-centered, academic approach. I would switch it to 'Linguists and Researchers', maybe. 

"Pre-existing solutions" sounds like a standard way to refer to a package, to me. To developers in my field (javascript community, startups), it means a package which does something that I would otherwise have to developer - it doesn't mean a panacea.

**Comment by cesine** [comment]
sorry guys, I'll close this PR. 

I just wanted more people to open the Personas.md file

**Comment by RichardLitt** [comment]
I still think this should be discussed in a wider issue.

**Pull request closed without merging**
