### PR TITLE
Update Standards used in Language Technology.md

### PR DESCRIPTION
**Pull request by HughP**
Added Character encoding as a section and ISO 15924 under scripts. Added a section for TC37.

### CODE REVIEW

**Comment by RichardLitt** [comment]
:+1:

**Comment by HughP** [comment]
@RichardLitt  So, I sent a Pull request to the copy under your personal github account. You updated with the merge. But how does the copy on the LowResourcedLanguages organization get updated? I am not clear what the relationship between the two versions is or how that is managed... I was thinking of triaging some of the issues in your repo, but then I noticed that there was no place to file new issues in the organizational location. - If it is easier to use google hangouts to explain this let me know.

**Comment by RichardLitt** [comment]
That copy has to be manually updated by fetching from upstream and pushing to origin. A fork is a copy at the time of forking - every change has to be manually applied (or you could use some sort of cron job). All issues remain on the original repository -- I believe there may be an option to turn these on for forks, but I'm not going to do that for now for that org. Triaging issues should be done on this repository. Have I given you contributor access to this repository yet?

**Comment by HughP** [comment]
No, on the commit access.

**Comment by RichardLitt** [comment]
Done now. :)

**Comment by HughP** [comment]
:+1:

**Pull request merged**
