### PR TITLE
encouraging visitors to star projects they like

### PR DESCRIPTION
**Pull request by cesine**
added stars for projects which are on github 
 * encourages visitors to "vote" for the projects they know and like by clicking on the starts button, and also meet other stargazers with similar interests
 * promotes projects which are more active 

0 stars is normal as we can see, and doesnt really mean anything. It could be a dormant project, a new project, or something that is just rare. 

Projects with a lot of stars are usually not LRL projects, but NLP projects used by regular developers. Having the star badge makes it easy to see these projects are clearly different from LRL but they are often useful too.

If you are looking for a type of technology you will probably look at all projects in that category (ie android apps) but the stars can give you a quick guess of which projects who might welcome you

Having stars on the list also encourages devs to get more stars on their own project, which is good for them.

Just looking at the page with stars shows how many projects are on github which might mean they have a chance at getting collaborators which is cool!

screen shot 2015-08-02 at 1 00 01 pm

### CODE REVIEW

**Comment by RichardLitt** [comment]
This is a great idea! Awesome.

**Comment by cesine** [comment]
I added an experiment in our about repo to see if adding stars will help projects visibility over time. I did a baseline measure yesterday of stats for all projects. I dont have time to work on it today but before next sunday I'll make a cron job which extracts the info weekly.

**Comment by HughP** [comment]
This is awesome... Great idea @cesine ... thinking this through though, if a project has several sub-components, then does the stars method really help promote those sub-components?
Let's take SIL's FLEx for a moment. There is FLEx proper and then there is FLEx tools, a separate collection of python scripts for cleaning up FLEx XML DBs. I would expect FLEx to have more stars than FLEx tools, but it does not mean that FLEx tools is "abandon-ware" even if it has no stars... stars in this case is mostly developers saying "we use this"... which is different than a language community saying "we used this tool to overcome our under-resourced language status".

**Comment by RichardLitt** [comment]
@HughP That's an edge case. I wouldn't worry about it.

**Pull request merged**
