### PR TITLE
Fix typographical error(s)

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@RichardLitt, I've corrected a typographical error in the documentation of the [endangered-languages](https://github.com/RichardLitt/endangered-languages) project. Specifically, I've changed comparitive to comparative. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by RichardLitt** [comment]
I hate to be a pedant, but... "Linguistic squalor" makes no sense. Linguistics is the study of language, and is generally divided into two camps - descriptivists and prescriptivists. The first, generally academic linguists and the norm, describe languages without judgements about language usage. The second arbitrarily decided some usages were better than others, mostly based on upper class literary dialects. Another word for these linguists are grammar nazis or pedants. To use the word linguistic to define them doesn't really work, even if you are a pedant, because it ignores the descriptivists. 

Just sayin.

**Comment by thoppe** [comment]
Sage advice to a lowly bot, I'll make sure he gets it. If you'd like to suggest an alternative that retains the same sassy and slightly off-putting nature, I'll consider immortalizing your words in hundreds of PR to be issued in the future. To be precise and as a question, would the phrase "prescriptivist linguistic squalor" make sense?

As a slight digression, I want to geek out about the original repo that was corrected. This is such an amazing project -- one that I would have never found, nor thought to look for, had you not made a typographical error*. 

*I am assuming that this was [simply a slip of the finger](https://en.wikipedia.org/wiki/Typographical_error) and not a mistake made in ignorance.

**Comment by thoppe** [comment]
@cesine [suggests](https://github.com/thoppe/orthographic-pedant/pull/24) the phrase "orthographic squalor" as an alternative. To me, it doesn't have the same oomph and it's already part of the name of the project. What do you think @RichardLitt?

**Comment by RichardLitt** [comment]
Orthographic works great - @cesine's fix is perfect. 

And thanks! It's a labor of love, this project. :)

**Comment by RichardLitt** [comment]
I think it has the same oomph, to me, and it should match the project name.

**Pull request merged**
