### PR TITLE
HughP patch 2

### PR DESCRIPTION
**Pull request by HughP**
Two, things - Both related.
1. I created an entry template file. (I expect some discussion around this.) The idea is that if we advertise this list broadly then how do we want contributors to add data? and which data?
2. I added a sentence in the main list file to reference this template file. Of course this second bit is not dependent logically on the first, but it seems that they would go together. 

The larger issue I think is how we have been discussing list depth. Maybe if we organize the data appropriately we could use a CLLD app for presentation, and aggregation to OLAC? perhaps @xrotwang might be able to speak to this. With a tool like this we might be able to get an assessment of which languages are "severely" under resourced, and under resourced in which ways.

### CODE REVIEW

**Comment by HughP** [comment]
Depending on the documentation and direction we are headed in the call we might consider: http://dublincore.org/groups/tools/map.shtml
http://dublincore.org/documents/dcmi-terms/#terms-language

**Comment by xrotwang** [comment]
I'm not sure that it is possible to gather information on this level of detail for many of the currently listed projects. On the other hand most of this information is easily discoverable for some projects, e.g. a python package like `clld` typically has a [``setup.py``](https://github.com/clld/clld/blob/master/setup.py#L83-L118) file listing some of the properties from the template.

Regarding using a `clld` app to present this information: While this would support aggregation with OLAC, I think it would only make sense if most items listed are tagged with languages they may be applied to.

Anyway, I think a clearer picture of how this list is supposed to be used is necessary to answer these questions.

**Comment by RichardLitt** [comment]
So, the entry template file definitely brings up a lot of interesting questions. Right now, the list is minimal, and is geared towards people being able to edit it without a second thought - all you do is add in a link and a description, and the description is normally just the repository description. What you're suggesting here is some sort of massive object notation or template for each link, which would add a lot of time costs (while also being very useful). I just wonder whether it's too much - it is likely to overwhelm anyone who wanted to add projects to this list on the fly. The other problem is that the list is no longer a simple list anymore, and we'd have to start thinking about a wider database. I guess that is OK, but it means that data entry and display is entirely different. I'm worried about that. 

I agree that the template you provide is maximally interesting - getting that much information on different projects may not be possible. 

I don't think that items should be tagged according to languages they apply to and left at that - a lot of the items in the current list aren't aimed at a specific language, at all. 

I think, if we're going to start making a database like this, it'd be best to think about how users are going to access it and add to it, first. If we're building an app, we've really got to think about the UI a lot more, or we end up with something that is potentially useful but not used by any one. 

@xrotwang the list is mean to be a database of open source products for anyone interested in low resource languages, as a starting place for deeper research. Basically - what is out there, right now. Currently, it's hard to find a list of open source software for low resource languages, at all.

**Comment by RichardLitt** [comment]
Landed in f33e10ef650518a1f7f31678674c405c2deae3fa. Merged because it might be necessary to list this at some point if we want to make a more sophisticated ontology, and because the Personas file should be filled out more. I'm not convinced about using another mechanism for presentation, like a CLLD app, nor about aggregation and addition into OLAC, mostly because I don't interface with either of those much (which may be something I need to change).

**Pull request closed without merging**
