### PR TITLE
Edited Pomo Family, Added Open-Source Templates

### PR DESCRIPTION
**Pull request by eddersko**
Edited the Pomo family section to include Kashaya and Northern Pomo language apps, and the Northern Pomo website.
Added Template for Word-Learning App.
Added Template for Multilayered Language Learning Resources.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks @eddersko! Awesome.

Regarding the Pomo resources - while links to resources themselves are great, we're only looking for links to the source code for those resources here. Is the code for the website // iOS & android app available publicly? If not, I can only accept the first two repository links.

**Comment by eddersko** [comment]
Okay, that's fine - yeah the code for the website and Android app are the 'Template for...' so you can keep those, and take out the whole Pomo section.

**Comment by RichardLitt** [comment]
Cool. What happened to the pomo dictionary? Did you rename it?

**Comment by eddersko** [comment]
Yep, that is now Template for Word-Learning App under Android Applications.

**Comment by RichardLitt** [comment]
Merged. Thanks!

**Pull request merged**
